# Generated by Django 5.2.14 on 2026-05-18 14:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.CharField(max_length=255, verbose_name='Адрес подачи')),
                ('dropoff_address', models.CharField(max_length=255, verbose_name='Адрес назначения')),
                ('pickup_time', models.DateTimeField(verbose_name='Время подачи')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Введите телефон в формате +79991234567.', regex='^\\+?\\d{10,15}$')], verbose_name='Телефон')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтвержден'), ('in_progress', 'В пути'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='new', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('estimated_distance_km', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Расстояние, км')),
                ('estimated_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ориентировочная стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтвержден'), ('in_progress', 'В пути'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], max_length=20, verbose_name='Статус')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Изменен')),
            ],
            options={
                'verbose_name': 'История статуса',
                'verbose_name_plural': 'История статусов',
                'ordering': ['-changed_at'],
            },
        ),
    ]
